name: Xiaomi SM6250 Kernel Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    # ADD THIS STEP FIRST TO INSTALL DEPENDENCIES
      - name: Install Coccinelle Dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y coccinelle
      - name: Android Kernel Build Action
        uses: dabao1955/kernel_build_action@v1.10.1
        with:
          kernel-url: https://github.com/ahksoft/android_kernel_xiaomi_sm6250
          kernel-branch: sixteen-qpr2
          config: defconfig
          arch: arm64
          android-version: 16
          
          # Fixed Toolchain (Clang r416183b is often r416183b1 in AOSP)
          #aosp-gcc: true
          aosp_clang_version: r547379 # Recommended stable version
          android_ndk: true
          aosp_gcc: false 
          # Built-in KernelSU Next Integration
          ksu: true
          ksu-other: true
          ksu-url: https://github.com/KernelSU-Next/KernelSU-Next
          ksu-version: legacy-susfs

          # Enables many DroidSpaces requirements (Namespaces, CGroups, OverlayFS)
          lxc: true
          lxc-patch: false
          
          # Packaging
          anykernel3: true
          release: true

          # NEW: Forces the compiler to output verbose, step-by-step logs 
          extra-cmd: V=1

  
